name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: '136'

    - name: Run tests
      env:
        SECRET_KEY: test-secret-key-that-is-32-characters-long-for-ci-testing
        OPENAI_API_KEY: test-openai-key-for-ci
        ANTHROPIC_API_KEY: test-anthropic-key-for-ci
        OPENROUTER_API_KEY: test-openrouter-key-for-ci
        NODE_ENV: test
      run: npm run test:ci
